### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Volem** [holidayapi/holidayapi-node#21]
Hi, 

We would like to use a proxy while using the HolidayAPI node sdk. Is there a support for this?

**Comment by joshtronic** [comment]
Hey Volem, currently our Node.js library does not feature any support for using a proxy to make network requests.

The library uses the `node-fetch` library which does appear to support using a proxy as per this issue / code:
https://github.com/node-fetch/node-fetch/issues/79

It shouldn't take much to update the `request` method to accept an additional `options` argument that could be used to inject the proxy information into the `fetch` call. 

First we've had a request for this, feel free to implement and submit a pull request. I'll leave the issue open in case I get to it before y'all do. Cheers!
