### ISSUE TITLE
2 Jan 2023 NYD (Observed) not being included in public holidays 

### ISSUE THREAD

**Issue by recipher** [holidayapi/holidayapi-node#38]
When I flip the public flag when calling the /holidays endpoint, the 2nd of January 2023 is not being included, although it is a public holiday. I've checked GB and US so far, and it's the same for both. NYD is included but not the actual national holiday.

Could this be fixed? Any ideas why it isn't included?

https://duckduckgo.com/?q=public+holidays+in+the+US+2023
https://duckduckgo.com/?q=public+holidays+in+the+UK+2023

**Comment by joshtronic** [comment]
You'll want to interrogate both the date and observed value that's returned from the API (actual result from the API using the Node lib):

```
    {                                                                                                                                                                                                                
      name: "New Year's Day",
      date: '2023-01-01',                            
      observed: '2023-01-02',
      public: true,                                                                                       
      country: 'US',                                 
      uuid: '82f78b8a-019e-479e-a19f-99040275f9bf',                                                       
      weekday: [Object]
    }, 
```

NYD lands on the 1st, but the inclusion of the 2nd (at least in US and GB) is an observance, and not an additional holiday. Some other countries explicitly have the 2nd of January off in addition to the 1st, and don't apply any additional observance logic to that

Hope this helps!

**Comment by recipher** [comment]
Hey, sorry for not replying (thought I had). This is great - I should have read the documentation better!
