### ISSUE TITLE
How Do You Decide What Holidays to Include?

### ISSUE THREAD

**Issue by recipher** [holidayapi/holidayapi-node#39]
So, for example in Canada, there are a few official holidays that are not returned from the API that timeandate.com think are holidays.

https://www.timeanddate.com/holidays/canada/2023?hol=1

So, Victoria Day is returned, but not Remembrance Day (or Boxing Day).

Also, for Canada, NYD doesn't show observed for the 2nd of January - why is that?

**Comment by joshtronic** [comment]
Hey @recipher, Remembrance / Boxing Day isn't a country-wide holiday in Canada, so you'll want to include subdivisions=true in the request (if your plan supports it). Depending on the province, those particular holidays may or may not be public holidays. If you visit https://holidayapi.com/countries/ca/2022 you can see the holidays listed there with the note "Only in certain states".

As for the January 2nd observance, to the best of my knowledge that's a government observance and not actually a public holiday (as per the Government of Canada website - https://www.canada.ca/en/revenue-agency/services/tax/public-holidays.html). We'll do some additional research on this one just to be certain, but we do try to use the official government resources as the gospel.

Feel free to reach out to hello@holidayapi.com if you have any further questions. Thanks!
