### ISSUE TITLE
Query multiple years

### ISSUE THREAD

**Issue by Mihailoff** [holidayapi/holidayapi-node#9]
Is it possible to query multiple years like multiple countries?

Like https://github.com/holidayapi/holidayapi-node#fetch-holidays-for-multiple-countries

```
holidayApi.holidays({
  country: 'CA',
  year: [2019, 2020]
})
```

**Comment by joshtronic** [comment]
Great question, unfortunately at present, there's no way to do that. Main reason is that the API doesn't support querying multiple years in the same way that it supports querying multiple countries. We could update the wrapper to allow it (and make 1 API call per year) but we like to favor keeping the wrappers in close parity with the service itself.

Definitely something for us to consider though, as it does come up somewhat regularly that folks want to pull ranges of data, to the point that we're actually working on a new endpoint that's a somewhat re-imagined version of the holidays endpoint that will allow a start and end date to be specified and all dates within the range will be returned with applicable data.

Hoping to have that rolled out in the next month, which will also mean we'll be updating this library to support the new stuff :)
